import {
  Brand,
  Category,
  Laptop,
  Sale,
  SaleItem,
  Warranty,
  LaptopService,
  ShopSettings,
  Profile,
  PaymentMethod,
} from "../types";

export const initialBrands: Brand[] = [
  { id: "b-1", name: "Dell", description: "Dell Laptops & Workstations" },
  { id: "b-2", name: "Lenovo", description: "Lenovo ThinkPad, Legion, IdeaPad, Yoga" },
  { id: "b-3", name: "Asus", description: "Asus ROG, TUF Gaming, ZenBook, VivoBook" },
  { id: "b-4", name: "Apple", description: "Apple MacBook Air & MacBook Pro" },
  { id: "b-5", name: "HP", description: "HP Spectre, Envy, OMEN, Pavilion, Victus" },
  { id: "b-6", name: "Acer", description: "Acer Nitro, Predator, Swift, Aspire" },
  { id: "b-7", name: "MSI", description: "MSI Gaming & Creator Laptops" },
];

export const initialCategories: Category[] = [
  { id: "c-1", name: "Business", description: "Corporate and office productivity" },
  { id: "c-2", name: "Gaming", description: "High-spec gaming laptops" },
  { id: "c-3", name: "Ultrabook", description: "Slim, light, and premium portable" },
  { id: "c-4", name: "Student / Budget", description: "Affordable everyday use" },
  { id: "c-5", name: "Workstation", description: "Heavy duty CAD/3D processing" },
];

// 40 Realistic Laptop Definitions
export const initialLaptops: Laptop[] = [
  // 1-8: Dell
  {
    id: "lap-1",
    brand_id: "b-1",
    category_id: "c-3",
    brand: initialBrands[0],
    category: initialCategories[2],
    model: "XPS 15 9530",
    product_code: "DELL-XPS-9530",
    serial_number: "DLXPS9530-001",
    cost_price: 3200000,
    selling_price: 3850000,
    stock_quantity: 4,
    warranty_period_months: 12,
    status: "in_stock",
    image_url: null,
    specifications: {
      laptop_id: "lap-1",
      cpu: "Intel Core i7-13700H",
      cpu_generation: "13th Gen",
      ram: "16GB",
      ram_type: "DDR5 4800MHz",
      storage: "1TB SSD",
      storage_type: "NVMe PCIe Gen4",
      gpu: "NVIDIA GeForce RTX 4050 6GB",
      display_size: "15.6 inch",
      display_resolution: "3456 x 2160 (3.5K OLED)",
      display_type: "OLED Touch",
      os: "Windows 11 Pro",
      battery: "6-cell 86Wh",
      battery_capacity: "86Wh",
      color: "Platinum Silver",
      weight: "1.92 kg",
      keyboard: "Backlit Chiclet Keyboard",
      backlit_keyboard: true,
      touchscreen: true,
      fingerprint: true,
      webcam: true,
      wifi: "Wi-Fi 6E (802.11ax)",
      bluetooth: "Bluetooth 5.2",
      usb_ports: "2x Thunderbolt 4, 1x USB-C 3.2 Gen 2",
      hdmi: false,
      other_specifications: "SD Card Reader, Waves MaxxAudio Pro",
    },
  },
  {
    id: "lap-2",
    brand_id: "b-1",
    category_id: "c-1",
    brand: initialBrands[0],
    category: initialCategories[0],
    model: "Latitude 5440",
    product_code: "DELL-LAT-5440",
    serial_number: "DLLAT5440-002",
    cost_price: 1800000,
    selling_price: 2150000,
    stock_quantity: 8,
    warranty_period_months: 36,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-2",
      cpu: "Intel Core i5-1335U",
      ram: "16GB",
      ram_type: "DDR4 3200MHz",
      storage: "512GB SSD",
      storage_type: "NVMe M.2",
      gpu: "Intel Iris Xe Graphics",
      display_size: "14.0 inch",
      display_resolution: "1920 x 1080 (FHD IPS)",
      os: "Windows 11 Pro",
      battery: "3-cell 54Wh",
      weight: "1.36 kg",
    },
  },
  {
    id: "lap-3",
    brand_id: "b-1",
    category_id: "c-2",
    brand: initialBrands[0],
    category: initialCategories[1],
    model: "G15 5530 Gaming",
    product_code: "DELL-G15-5530",
    serial_number: "DLG155530-003",
    cost_price: 2200000,
    selling_price: 2650000,
    stock_quantity: 3,
    warranty_period_months: 24,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-3",
      cpu: "Intel Core i7-13650HX",
      ram: "16GB",
      ram_type: "DDR5 4800MHz",
      storage: "512GB SSD",
      storage_type: "NVMe PCIe Gen4",
      gpu: "NVIDIA GeForce RTX 4060 8GB",
      display_size: "15.6 inch",
      display_resolution: "1920 x 1080 (165Hz FHD)",
      os: "Windows 11 Home",
      battery: "6-cell 86Wh",
      weight: "2.81 kg",
    },
  },
  {
    id: "lap-4",
    brand_id: "b-1",
    category_id: "c-4",
    brand: initialBrands[0],
    category: initialCategories[3],
    model: "Inspiron 15 3520",
    product_code: "DELL-INSP-3520",
    serial_number: "DLINSP3520-004",
    cost_price: 1100000,
    selling_price: 1350000,
    stock_quantity: 12,
    warranty_period_months: 12,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-4",
      cpu: "Intel Core i3-1215U",
      ram: "8GB",
      ram_type: "DDR4 2666MHz",
      storage: "256GB SSD",
      storage_type: "NVMe M.2",
      gpu: "Intel UHD Graphics",
      display_size: "15.6 inch",
      display_resolution: "1920 x 1080 (120Hz FHD)",
      os: "Windows 11 Home",
      battery: "3-cell 41Wh",
      weight: "1.65 kg",
    },
  },
  {
    id: "lap-5",
    brand_id: "b-1",
    category_id: "c-5",
    brand: initialBrands[0],
    category: initialCategories[4],
    model: "Precision 5680 Workstation",
    product_code: "DELL-PREC-5680",
    serial_number: "DLPREC5680-005",
    cost_price: 4500000,
    selling_price: 5400000,
    stock_quantity: 2,
    warranty_period_months: 36,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-5",
      cpu: "Intel Core i9-13900H",
      ram: "64GB",
      ram_type: "LPDDR5 6000MHz",
      storage: "2TB SSD",
      storage_type: "NVMe PCIe Gen4",
      gpu: "NVIDIA RTX 4000 Ada 12GB",
      display_size: "16.0 inch",
      display_resolution: "3840 x 2400 (UHD+ OLED)",
      os: "Windows 11 Pro",
      battery: "6-cell 100Wh",
      weight: "1.91 kg",
    },
  },
  {
    id: "lap-6",
    brand_id: "b-1",
    category_id: "c-3",
    brand: initialBrands[0],
    category: initialCategories[2],
    model: "XPS 13 Plus 9320",
    product_code: "DELL-XPS-9320",
    serial_number: "DLXPS9320-006",
    cost_price: 2600000,
    selling_price: 3100000,
    stock_quantity: 5,
    warranty_period_months: 12,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-6",
      cpu: "Intel Core i7-1360P",
      ram: "16GB",
      ram_type: "LPDDR5 6000MHz",
      storage: "512GB SSD",
      storage_type: "NVMe PCIe Gen4",
      gpu: "Intel Iris Xe Graphics",
      display_size: "13.4 inch",
      display_resolution: "1920 x 1200 (FHD+ IPS)",
      os: "Windows 11 Home",
      battery: "3-cell 55Wh",
      weight: "1.24 kg",
    },
  },

  // 7-13: Lenovo
  {
    id: "lap-7",
    brand_id: "b-2",
    category_id: "c-2",
    brand: initialBrands[1],
    category: initialCategories[1],
    model: "Legion Pro 5 16IRX8",
    product_code: "LNV-LEG-5P",
    serial_number: "LNVLEG5-007",
    cost_price: 2800000,
    selling_price: 3350000,
    stock_quantity: 2,
    warranty_period_months: 24,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-7",
      cpu: "Intel Core i7-13700HX",
      ram: "32GB",
      ram_type: "DDR5 5600MHz",
      storage: "1TB SSD",
      storage_type: "NVMe PCIe 4.0",
      gpu: "NVIDIA GeForce RTX 4060 8GB",
      display_size: "16.0 inch",
      display_resolution: "2560 x 1600 (240Hz WQXGA)",
      os: "Windows 11 Home",
      battery: "4-cell 80Wh",
      weight: "2.55 kg",
    },
  },
  {
    id: "lap-8",
    brand_id: "b-2",
    category_id: "c-1",
    brand: initialBrands[1],
    category: initialCategories[0],
    model: "ThinkPad X1 Carbon Gen 11",
    product_code: "LNV-X1C-G11",
    serial_number: "LNVX1C11-008",
    cost_price: 3100000,
    selling_price: 3750000,
    stock_quantity: 4,
    warranty_period_months: 36,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-8",
      cpu: "Intel Core i7-1365U vPro",
      ram: "32GB",
      ram_type: "LPDDR5 6400MHz",
      storage: "1TB SSD",
      storage_type: "NVMe PCIe 4.0 Performance",
      gpu: "Intel Iris Xe Graphics",
      display_size: "14.0 inch",
      display_resolution: "2880 x 1800 (2.8K OLED)",
      os: "Windows 11 Pro",
      battery: "4-cell 57Wh",
      weight: "1.12 kg",
    },
  },
  {
    id: "lap-9",
    brand_id: "b-2",
    category_id: "c-4",
    brand: initialBrands[1],
    category: initialCategories[3],
    model: "IdeaPad Slim 3 15IAH8",
    product_code: "LNV-IPS3-15",
    serial_number: "LNVIPS3-009",
    cost_price: 1050000,
    selling_price: 1280000,
    stock_quantity: 10,
    warranty_period_months: 12,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-9",
      cpu: "Intel Core i5-12450H",
      ram: "8GB",
      ram_type: "LPDDR5 4800MHz",
      storage: "512GB SSD",
      storage_type: "NVMe M.2",
      gpu: "Intel UHD Graphics",
      display_size: "15.6 inch",
      display_resolution: "1920 x 1080 (FHD IPS)",
      os: "Windows 11 Home",
      battery: "3-cell 47Wh",
      weight: "1.62 kg",
    },
  },
  {
    id: "lap-10",
    brand_id: "b-2",
    category_id: "c-3",
    brand: initialBrands[1],
    category: initialCategories[2],
    model: "Yoga 9i 2-in-1 14IRP8",
    product_code: "LNV-YOG-9I",
    serial_number: "LNVYOG9-010",
    cost_price: 2900000,
    selling_price: 3500000,
    stock_quantity: 3,
    warranty_period_months: 24,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-10",
      cpu: "Intel Core i7-1360P",
      ram: "16GB",
      ram_type: "LPDDR5 5200MHz",
      storage: "1TB SSD",
      storage_type: "NVMe PCIe 4.0",
      gpu: "Intel Iris Xe Graphics",
      display_size: "14.0 inch",
      display_resolution: "2880 x 1800 (OLED 90Hz Touch)",
      os: "Windows 11 Home",
      battery: "4-cell 75Wh",
      weight: "1.40 kg",
    },
  },
  {
    id: "lap-11",
    brand_id: "b-2",
    category_id: "c-2",
    brand: initialBrands[1],
    category: initialCategories[1],
    model: "LOQ 15IRH8 Gaming",
    product_code: "LNV-LOQ-15",
    serial_number: "LNVLOQ15-011",
    cost_price: 1950000,
    selling_price: 2350000,
    stock_quantity: 6,
    warranty_period_months: 24,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-11",
      cpu: "Intel Core i5-13420H",
      ram: "16GB",
      ram_type: "DDR5 5200MHz",
      storage: "512GB SSD",
      storage_type: "NVMe PCIe 4.0",
      gpu: "NVIDIA GeForce RTX 3050 6GB",
      display_size: "15.6 inch",
      display_resolution: "1920 x 1080 (144Hz FHD)",
      os: "Windows 11 Home",
      battery: "4-cell 60Wh",
      weight: "2.40 kg",
    },
  },
  {
    id: "lap-12",
    brand_id: "b-2",
    category_id: "c-1",
    brand: initialBrands[1],
    category: initialCategories[0],
    model: "ThinkPad E14 Gen 5",
    product_code: "LNV-TP-E14",
    serial_number: "LNVTPE14-012",
    cost_price: 1550000,
    selling_price: 1850000,
    stock_quantity: 7,
    warranty_period_months: 24,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-12",
      cpu: "AMD Ryzen 5 7530U",
      ram: "16GB",
      ram_type: "DDR4 3200MHz",
      storage: "512GB SSD",
      storage_type: "NVMe M.2",
      gpu: "AMD Radeon Graphics",
      display_size: "14.0 inch",
      display_resolution: "1920 x 1200 (WUXGA IPS)",
      os: "Windows 11 Pro",
      battery: "3-cell 47Wh",
      weight: "1.41 kg",
    },
  },

  // 13-18: Asus
  {
    id: "lap-13",
    brand_id: "b-3",
    category_id: "c-2",
    brand: initialBrands[2],
    category: initialCategories[1],
    model: "ROG Zephyrus G14 GA402",
    product_code: "ASUS-ROG-G14",
    serial_number: "ASUSROG14-013",
    cost_price: 3400000,
    selling_price: 4100000,
    stock_quantity: 3,
    warranty_period_months: 24,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-13",
      cpu: "AMD Ryzen 9 7940HS",
      ram: "32GB",
      ram_type: "DDR5 4800MHz",
      storage: "1TB SSD",
      storage_type: "NVMe PCIe 4.0",
      gpu: "NVIDIA GeForce RTX 4070 8GB",
      display_size: "14.0 inch",
      display_resolution: "2560 x 1600 (ROG Nebula 165Hz)",
      os: "Windows 11 Home",
      battery: "4-cell 76Wh",
      weight: "1.65 kg",
    },
  },
  {
    id: "lap-14",
    brand_id: "b-3",
    category_id: "c-2",
    brand: initialBrands[2],
    category: initialCategories[1],
    model: "TUF Gaming A15 FA507",
    product_code: "ASUS-TUF-A15",
    serial_number: "ASUSTUFA15-014",
    cost_price: 2100000,
    selling_price: 2550000,
    stock_quantity: 5,
    warranty_period_months: 24,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-14",
      cpu: "AMD Ryzen 7 7735HS",
      ram: "16GB",
      ram_type: "DDR5 4800MHz",
      storage: "512GB SSD",
      storage_type: "NVMe PCIe 4.0",
      gpu: "NVIDIA GeForce RTX 4050 6GB",
      display_size: "15.6 inch",
      display_resolution: "1920 x 1080 (144Hz FHD)",
      os: "Windows 11 Home",
      battery: "4-cell 90Wh",
      weight: "2.20 kg",
    },
  },
  {
    id: "lap-15",
    brand_id: "b-3",
    category_id: "c-3",
    brand: initialBrands[2],
    category: initialCategories[2],
    model: "ZenBook 14 OLED UX3405",
    product_code: "ASUS-ZEN-14",
    serial_number: "ASUSZEN14-015",
    cost_price: 2400000,
    selling_price: 2900000,
    stock_quantity: 4,
    warranty_period_months: 24,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-15",
      cpu: "Intel Core Ultra 7 155H (AI Boost)",
      ram: "16GB",
      ram_type: "LPDDR5X 7467MHz",
      storage: "1TB SSD",
      storage_type: "NVMe PCIe 4.0",
      gpu: "Intel Arc Graphics",
      display_size: "14.0 inch",
      display_resolution: "2880 x 1800 (120Hz 3K OLED)",
      os: "Windows 11 Home",
      battery: "4-cell 75Wh",
      weight: "1.20 kg",
    },
  },
  {
    id: "lap-16",
    brand_id: "b-3",
    category_id: "c-4",
    brand: initialBrands[2],
    category: initialCategories[3],
    model: "VivoBook 15 X1504",
    product_code: "ASUS-VIVO-15",
    serial_number: "ASUSVIV15-016",
    cost_price: 1150000,
    selling_price: 1380000,
    stock_quantity: 9,
    warranty_period_months: 12,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-16",
      cpu: "Intel Core i5-1235U",
      ram: "8GB",
      ram_type: "DDR4 3200MHz",
      storage: "512GB SSD",
      storage_type: "NVMe M.2",
      gpu: "Intel Iris Xe Graphics",
      display_size: "15.6 inch",
      display_resolution: "1920 x 1080 (FHD IPS)",
      os: "Windows 11 Home",
      battery: "3-cell 42Wh",
      weight: "1.70 kg",
    },
  },
  {
    id: "lap-17",
    brand_id: "b-3",
    category_id: "c-2",
    brand: initialBrands[2],
    category: initialCategories[1],
    model: "ROG Strix SCAR 16 G634",
    product_code: "ASUS-ROG-SCAR16",
    serial_number: "ASUSSCAR16-017",
    cost_price: 4900000,
    selling_price: 5800000,
    stock_quantity: 2,
    warranty_period_months: 24,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-17",
      cpu: "Intel Core i9-13980HX",
      ram: "32GB",
      ram_type: "DDR5 4800MHz",
      storage: "2TB SSD",
      storage_type: "NVMe PCIe 4.0 Performance",
      gpu: "NVIDIA GeForce RTX 4080 12GB",
      display_size: "16.0 inch",
      display_resolution: "2560 x 1600 (Mini-LED 240Hz)",
      os: "Windows 11 Home",
      battery: "4-cell 90Wh",
      weight: "2.60 kg",
    },
  },

  // 18-24: Apple
  {
    id: "lap-18",
    brand_id: "b-4",
    category_id: "c-3",
    brand: initialBrands[3],
    category: initialCategories[2],
    model: "MacBook Air 13 M2",
    product_code: "APL-MBA-M2-13",
    serial_number: "APLMBA13-018",
    cost_price: 2400000,
    selling_price: 2850000,
    stock_quantity: 6,
    warranty_period_months: 12,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-18",
      cpu: "Apple M2 (8-Core CPU)",
      ram: "8GB",
      ram_type: "Unified Memory",
      storage: "256GB SSD",
      storage_type: "Apple SSD",
      gpu: "Apple 8-Core GPU",
      display_size: "13.6 inch",
      display_resolution: "2560 x 1664 (Liquid Retina)",
      os: "macOS Sonoma",
      battery: "52.6Wh Li-Po",
      weight: "1.24 kg",
    },
  },
  {
    id: "lap-19",
    brand_id: "b-4",
    category_id: "c-3",
    brand: initialBrands[3],
    category: initialCategories[2],
    model: "MacBook Air 15 M3",
    product_code: "APL-MBA-M3-15",
    serial_number: "APLMBA15-019",
    cost_price: 3100000,
    selling_price: 3650000,
    stock_quantity: 5,
    warranty_period_months: 12,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-19",
      cpu: "Apple M3 (8-Core CPU)",
      ram: "16GB",
      ram_type: "Unified Memory",
      storage: "512GB SSD",
      storage_type: "Apple SSD",
      gpu: "Apple 10-Core GPU",
      display_size: "15.3 inch",
      display_resolution: "2880 x 1864 (Liquid Retina)",
      os: "macOS Sonoma",
      battery: "66.5Wh Li-Po",
      weight: "1.51 kg",
    },
  },
  {
    id: "lap-20",
    brand_id: "b-4",
    category_id: "c-5",
    brand: initialBrands[3],
    category: initialCategories[4],
    model: "MacBook Pro 14 M3 Pro",
    product_code: "APL-MBP-M3P-14",
    serial_number: "APLMBP14-020",
    cost_price: 4500000,
    selling_price: 5350000,
    stock_quantity: 3,
    warranty_period_months: 12,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-20",
      cpu: "Apple M3 Pro (11-Core CPU)",
      ram: "18GB",
      ram_type: "Unified Memory",
      storage: "512GB SSD",
      storage_type: "Apple SSD",
      gpu: "Apple 14-Core GPU",
      display_size: "14.2 inch",
      display_resolution: "3024 x 1964 (Liquid Retina XDR 120Hz ProMotion)",
      os: "macOS Sonoma",
      battery: "70Wh Li-Po",
      weight: "1.61 kg",
    },
  },
  {
    id: "lap-21",
    brand_id: "b-4",
    category_id: "c-5",
    brand: initialBrands[3],
    category: initialCategories[4],
    model: "MacBook Pro 16 M3 Max",
    product_code: "APL-MBP-M3MAX-16",
    serial_number: "APLMBP16-021",
    cost_price: 7200000,
    selling_price: 8400000,
    stock_quantity: 1,
    warranty_period_months: 12,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-21",
      cpu: "Apple M3 Max (14-Core CPU)",
      ram: "36GB",
      ram_type: "Unified Memory",
      storage: "1TB SSD",
      storage_type: "Apple SSD",
      gpu: "Apple 30-Core GPU",
      display_size: "16.2 inch",
      display_resolution: "3456 x 2234 (Liquid Retina XDR 120Hz ProMotion)",
      os: "macOS Sonoma",
      battery: "100Wh Li-Po",
      weight: "2.16 kg",
    },
  },
  {
    id: "lap-22",
    brand_id: "b-4",
    category_id: "c-4",
    brand: initialBrands[3],
    category: initialCategories[3],
    model: "MacBook Air 13 M1",
    product_code: "APL-MBA-M1-13",
    serial_number: "APLMBA13-022",
    cost_price: 1800000,
    selling_price: 2150000,
    stock_quantity: 8,
    warranty_period_months: 12,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-22",
      cpu: "Apple M1 (8-Core CPU)",
      ram: "8GB",
      ram_type: "Unified Memory",
      storage: "256GB SSD",
      storage_type: "Apple SSD",
      gpu: "Apple 7-Core GPU",
      display_size: "13.3 inch",
      display_resolution: "2560 x 1600 (Retina)",
      os: "macOS Ventura",
      battery: "49.9Wh Li-Po",
      weight: "1.29 kg",
    },
  },

  // 23-29: HP
  {
    id: "lap-23",
    brand_id: "b-5",
    category_id: "c-3",
    brand: initialBrands[4],
    category: initialCategories[2],
    model: "Spectre x360 14 2-in-1",
    product_code: "HP-SPEC-14",
    serial_number: "HPSPEC14-023",
    cost_price: 2950000,
    selling_price: 3550000,
    stock_quantity: 4,
    warranty_period_months: 24,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-23",
      cpu: "Intel Core Ultra 7 155H",
      ram: "16GB",
      ram_type: "LPDDR5X 6400MHz",
      storage: "1TB SSD",
      storage_type: "NVMe PCIe Gen4",
      gpu: "Intel Arc Graphics",
      display_size: "14.0 inch",
      display_resolution: "2880 x 1800 (OLED 120Hz Touch)",
      os: "Windows 11 Home",
      battery: "4-cell 68Wh",
      weight: "1.44 kg",
    },
  },
  {
    id: "lap-24",
    brand_id: "b-5",
    category_id: "c-2",
    brand: initialBrands[4],
    category: initialCategories[1],
    model: "OMEN 16 Gaming",
    product_code: "HP-OMEN-16",
    serial_number: "HPOMEN16-024",
    cost_price: 2900000,
    selling_price: 3450000,
    stock_quantity: 3,
    warranty_period_months: 24,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-24",
      cpu: "Intel Core i7-13700HX",
      ram: "16GB",
      ram_type: "DDR5 4800MHz",
      storage: "1TB SSD",
      storage_type: "NVMe PCIe Gen4",
      gpu: "NVIDIA GeForce RTX 4070 8GB",
      display_size: "16.1 inch",
      display_resolution: "2560 x 1440 (QHD 240Hz)",
      os: "Windows 11 Home",
      battery: "6-cell 83Wh",
      weight: "2.35 kg",
    },
  },
  {
    id: "lap-25",
    brand_id: "b-5",
    category_id: "c-2",
    brand: initialBrands[4],
    category: initialCategories[1],
    model: "Victus 15 Gaming",
    product_code: "HP-VIC-15",
    serial_number: "HPVIC15-025",
    cost_price: 1650000,
    selling_price: 1980000,
    stock_quantity: 7,
    warranty_period_months: 24,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-25",
      cpu: "Intel Core i5-13420H",
      ram: "16GB",
      ram_type: "DDR4 3200MHz",
      storage: "512GB SSD",
      storage_type: "NVMe M.2",
      gpu: "NVIDIA GeForce RTX 3050 6GB",
      display_size: "15.6 inch",
      display_resolution: "1920 x 1080 (144Hz FHD)",
      os: "Windows 11 Home",
      battery: "4-cell 70Wh",
      weight: "2.29 kg",
    },
  },
  {
    id: "lap-26",
    brand_id: "b-5",
    category_id: "c-4",
    brand: initialBrands[4],
    category: initialCategories[3],
    model: "Pavilion 15 EG3000",
    product_code: "HP-PAV-15",
    serial_number: "HPPAV15-026",
    cost_price: 1250000,
    selling_price: 1520000,
    stock_quantity: 9,
    warranty_period_months: 12,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-26",
      cpu: "Intel Core i5-1335U",
      ram: "8GB",
      ram_type: "DDR4 3200MHz",
      storage: "512GB SSD",
      storage_type: "NVMe M.2",
      gpu: "Intel Iris Xe Graphics",
      display_size: "15.6 inch",
      display_resolution: "1920 x 1080 (FHD IPS)",
      os: "Windows 11 Home",
      battery: "3-cell 41Wh",
      weight: "1.74 kg",
    },
  },
  {
    id: "lap-27",
    brand_id: "b-5",
    category_id: "c-1",
    brand: initialBrands[4],
    category: initialCategories[0],
    model: "EliteBook 840 G10",
    product_code: "HP-ELITE-840",
    serial_number: "HPELT840-027",
    cost_price: 2400000,
    selling_price: 2950000,
    stock_quantity: 5,
    warranty_period_months: 36,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-27",
      cpu: "Intel Core i7-1355U",
      ram: "16GB",
      ram_type: "DDR5 5200MHz",
      storage: "512GB SSD",
      storage_type: "NVMe PCIe Gen4",
      gpu: "Intel Iris Xe Graphics",
      display_size: "14.0 inch",
      display_resolution: "1920 x 1200 (WUXGA IPS 400nits)",
      os: "Windows 11 Pro",
      battery: "3-cell 51Wh",
      weight: "1.36 kg",
    },
  },

  // 28-34: Acer
  {
    id: "lap-28",
    brand_id: "b-6",
    category_id: "c-2",
    brand: initialBrands[5],
    category: initialCategories[1],
    model: "Predator Helios 16 PH16",
    product_code: "ACR-PRED-16",
    serial_number: "ACRPRED16-028",
    cost_price: 3500000,
    selling_price: 4200000,
    stock_quantity: 3,
    warranty_period_months: 24,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-28",
      cpu: "Intel Core i7-13700HX",
      ram: "32GB",
      ram_type: "DDR5 5600MHz",
      storage: "1TB SSD",
      storage_type: "NVMe PCIe Gen4",
      gpu: "NVIDIA GeForce RTX 4070 8GB",
      display_size: "16.0 inch",
      display_resolution: "2560 x 1600 (WQXGA 240Hz IPS)",
      os: "Windows 11 Home",
      battery: "4-cell 90Wh",
      weight: "2.60 kg",
    },
  },
  {
    id: "lap-29",
    brand_id: "b-6",
    category_id: "c-2",
    brand: initialBrands[5],
    category: initialCategories[1],
    model: "Nitro V 15 ANV15",
    product_code: "ACR-NITRO-V15",
    serial_number: "ACRNITRO15-029",
    cost_price: 1750000,
    selling_price: 2100000,
    stock_quantity: 6,
    warranty_period_months: 24,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-29",
      cpu: "Intel Core i5-13420H",
      ram: "16GB",
      ram_type: "DDR5 5200MHz",
      storage: "512GB SSD",
      storage_type: "NVMe PCIe Gen4",
      gpu: "NVIDIA GeForce RTX 4050 6GB",
      display_size: "15.6 inch",
      display_resolution: "1920 x 1080 (144Hz FHD IPS)",
      os: "Windows 11 Home",
      battery: "4-cell 57Wh",
      weight: "2.11 kg",
    },
  },
  {
    id: "lap-30",
    brand_id: "b-6",
    category_id: "c-3",
    brand: initialBrands[5],
    category: initialCategories[2],
    model: "Swift Go 14 SFG14",
    product_code: "ACR-SWIFT-14",
    serial_number: "ACRSWIFT14-030",
    cost_price: 1950000,
    selling_price: 2350000,
    stock_quantity: 5,
    warranty_period_months: 24,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-30",
      cpu: "Intel Core Ultra 5 125H",
      ram: "16GB",
      ram_type: "LPDDR5X 6400MHz",
      storage: "512GB SSD",
      storage_type: "NVMe PCIe Gen4",
      gpu: "Intel Arc Graphics",
      display_size: "14.0 inch",
      display_resolution: "2880 x 1800 (2.8K 90Hz OLED)",
      os: "Windows 11 Home",
      battery: "3-cell 65Wh",
      weight: "1.32 kg",
    },
  },
  {
    id: "lap-31",
    brand_id: "b-6",
    category_id: "c-4",
    brand: initialBrands[5],
    category: initialCategories[3],
    model: "Aspire 5 A515",
    product_code: "ACR-ASP-5",
    serial_number: "ACRASP5-031",
    cost_price: 1100000,
    selling_price: 1320000,
    stock_quantity: 11,
    warranty_period_months: 12,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-31",
      cpu: "Intel Core i3-1315U",
      ram: "8GB",
      ram_type: "LPDDR5",
      storage: "512GB SSD",
      storage_type: "NVMe M.2",
      gpu: "Intel UHD Graphics",
      display_size: "15.6 inch",
      display_resolution: "1920 x 1080 (FHD IPS)",
      os: "Windows 11 Home",
      battery: "3-cell 50Wh",
      weight: "1.78 kg",
    },
  },

  // 32-40: MSI & Premium Workstations
  {
    id: "lap-32",
    brand_id: "b-7",
    category_id: "c-2",
    brand: initialBrands[6],
    category: initialCategories[1],
    model: "Katana 15 B13VFK",
    product_code: "MSI-KAT-15",
    serial_number: "MSIKAT15-032",
    cost_price: 2350000,
    selling_price: 2800000,
    stock_quantity: 4,
    warranty_period_months: 24,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-32",
      cpu: "Intel Core i7-13620H",
      ram: "16GB",
      ram_type: "DDR5 5200MHz",
      storage: "1TB SSD",
      storage_type: "NVMe PCIe Gen4",
      gpu: "NVIDIA GeForce RTX 4060 8GB",
      display_size: "15.6 inch",
      display_resolution: "1920 x 1080 (144Hz FHD IPS)",
      os: "Windows 11 Home",
      battery: "3-cell 53.5Wh",
      weight: "2.25 kg",
    },
  },
  {
    id: "lap-33",
    brand_id: "b-7",
    category_id: "c-2",
    brand: initialBrands[6],
    category: initialCategories[1],
    model: "Raider GE78 HX 13VI",
    product_code: "MSI-RAID-GE78",
    serial_number: "MSIRAID78-033",
    cost_price: 6800000,
    selling_price: 7950000,
    stock_quantity: 1,
    warranty_period_months: 24,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-33",
      cpu: "Intel Core i9-13980HX",
      ram: "64GB",
      ram_type: "DDR5 5600MHz",
      storage: "2TB SSD",
      storage_type: "NVMe PCIe Gen5 Ready",
      gpu: "NVIDIA GeForce RTX 4090 16GB",
      display_size: "17.0 inch",
      display_resolution: "2560 x 1600 (QHD+ 240Hz)",
      os: "Windows 11 Pro",
      battery: "4-cell 99.9Wh",
      weight: "3.10 kg",
    },
  },
  {
    id: "lap-34",
    brand_id: "b-7",
    category_id: "c-3",
    brand: initialBrands[6],
    category: initialCategories[2],
    model: "Prestige 14 AI Evo",
    product_code: "MSI-PRES-14",
    serial_number: "MSIPRES14-034",
    cost_price: 2500000,
    selling_price: 2980000,
    stock_quantity: 3,
    warranty_period_months: 24,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-34",
      cpu: "Intel Core Ultra 7 155H",
      ram: "16GB",
      ram_type: "LPDDR5X",
      storage: "1TB SSD",
      storage_type: "NVMe PCIe Gen4",
      gpu: "Intel Arc Graphics",
      display_size: "14.0 inch",
      display_resolution: "2880 x 1800 (2.8K 120Hz OLED)",
      os: "Windows 11 Home",
      battery: "4-cell 90Wh",
      weight: "1.70 kg",
    },
  },
  {
    id: "lap-35",
    brand_id: "b-7",
    category_id: "c-4",
    brand: initialBrands[6],
    category: initialCategories[3],
    model: "Modern 14 C12MO",
    product_code: "MSI-MOD-14",
    serial_number: "MSIMOD14-035",
    cost_price: 950000,
    selling_price: 1180000,
    stock_quantity: 14,
    warranty_period_months: 12,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-35",
      cpu: "Intel Core i3-1215U",
      ram: "8GB",
      ram_type: "DDR4 3200MHz",
      storage: "512GB SSD",
      storage_type: "NVMe M.2",
      gpu: "Intel UHD Graphics",
      display_size: "14.0 inch",
      display_resolution: "1920 x 1080 (FHD IPS)",
      os: "Windows 11 Home",
      battery: "3-cell 39.3Wh",
      weight: "1.40 kg",
    },
  },
  {
    id: "lap-36",
    brand_id: "b-7",
    category_id: "c-2",
    brand: initialBrands[6],
    category: initialCategories[1],
    model: "Cyborg 15 A12VE",
    product_code: "MSI-CYB-15",
    serial_number: "MSICYB15-036",
    cost_price: 1850000,
    selling_price: 2200000,
    stock_quantity: 6,
    warranty_period_months: 24,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-36",
      cpu: "Intel Core i5-12450H",
      ram: "16GB",
      ram_type: "DDR5 4800MHz",
      storage: "512GB SSD",
      storage_type: "NVMe PCIe Gen4",
      gpu: "NVIDIA GeForce RTX 4050 6GB",
      display_size: "15.6 inch",
      display_resolution: "1920 x 1080 (144Hz FHD)",
      os: "Windows 11 Home",
      battery: "3-cell 53.5Wh",
      weight: "1.98 kg",
    },
  },
  {
    id: "lap-37",
    brand_id: "b-1",
    category_id: "c-1",
    brand: initialBrands[0],
    category: initialCategories[0],
    model: "Vostro 3530",
    product_code: "DELL-VOST-3530",
    serial_number: "DLVOST3530-037",
    cost_price: 1200000,
    selling_price: 1450000,
    stock_quantity: 8,
    warranty_period_months: 12,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-37",
      cpu: "Intel Core i5-1335U",
      ram: "8GB",
      ram_type: "DDR4 3200MHz",
      storage: "512GB SSD",
      storage_type: "NVMe M.2",
      gpu: "Intel Iris Xe Graphics",
      display_size: "15.6 inch",
      display_resolution: "1920 x 1080 (120Hz FHD)",
      os: "Windows 11 Pro",
      battery: "3-cell 41Wh",
      weight: "1.66 kg",
    },
  },
  {
    id: "lap-38",
    brand_id: "b-2",
    category_id: "c-5",
    brand: initialBrands[1],
    category: initialCategories[4],
    model: "ThinkPad P16 Gen 2",
    product_code: "LNV-TP-P16G2",
    serial_number: "LNVTPP16-038",
    cost_price: 5200000,
    selling_price: 6300000,
    stock_quantity: 2,
    warranty_period_months: 36,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-38",
      cpu: "Intel Core i9-13950HX vPro",
      ram: "64GB",
      ram_type: "DDR5 5600MHz ECC",
      storage: "2TB SSD",
      storage_type: "NVMe PCIe Gen4 Performance",
      gpu: "NVIDIA RTX 3500 Ada 12GB",
      display_size: "16.0 inch",
      display_resolution: "3840 x 2400 (WQUXGA OLED 500nits)",
      os: "Windows 11 Pro",
      battery: "6-cell 94Wh",
      weight: "2.95 kg",
    },
  },
  {
    id: "lap-39",
    brand_id: "b-3",
    category_id: "c-3",
    brand: initialBrands[2],
    category: initialCategories[2],
    model: "ZenBook Duo 2024 UX8406",
    product_code: "ASUS-ZEN-DUO",
    serial_number: "ASUSZENDUO-039",
    cost_price: 4300000,
    selling_price: 5100000,
    stock_quantity: 3,
    warranty_period_months: 24,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-39",
      cpu: "Intel Core Ultra 9 185H",
      ram: "32GB",
      ram_type: "LPDDR5X 7467MHz",
      storage: "1TB SSD",
      storage_type: "NVMe PCIe 4.0",
      gpu: "Intel Arc Graphics",
      display_size: "14.0 inch",
      display_resolution: "Dual 2880 x 1800 (120Hz 3K OLED)",
      os: "Windows 11 Pro",
      battery: "4-cell 75Wh",
      weight: "1.35 kg",
    },
  },
  {
    id: "lap-40",
    brand_id: "b-5",
    category_id: "c-1",
    brand: initialBrands[4],
    category: initialCategories[0],
    model: "ProBook 450 G10",
    product_code: "HP-PRO-450",
    serial_number: "HPPRO450-040",
    cost_price: 1600000,
    selling_price: 1920000,
    stock_quantity: 7,
    warranty_period_months: 24,
    status: "in_stock",
    specifications: {
      laptop_id: "lap-40",
      cpu: "Intel Core i5-1335U",
      ram: "16GB",
      ram_type: "DDR4 3200MHz",
      storage: "512GB SSD",
      storage_type: "NVMe M.2",
      gpu: "Intel Iris Xe Graphics",
      display_size: "15.6 inch",
      display_resolution: "1920 x 1080 (FHD IPS)",
      os: "Windows 11 Pro",
      battery: "3-cell 51Wh",
      weight: "1.79 kg",
    },
  },
];

// Helper customer names & phones for realistic transactions
const myanmarCustomerNames = [
  "U Aung Ko Win", "Daw Thin Thin Aye", "Ko Min Thu", "Ma Su Myat Noe", "U Hlaing Bwa",
  "Daw Khin Mar Lar", "Ko Zaw Myo Htet", "Ma Hnin Ei Phyu", "Ko Sai Lu", "Daw Nan Kham",
  "U Tun Tun Win", "Ma Theint Theint Thu", "Ko Kyaw Zin", "Ma Phyu Phyu Win", "U Bo Bo",
  "Daw Nilar Win", "Ko Thura Zaw", "Ma May Thu Aung", "Ko Naing Lin", "Daw Mya Mya Khin",
  "U Myo Min Lat", "Ma Aye Chan Moe", "Ko Zin Ko Ko", "Daw Sandar Win", "Ko Chit Ko Ko",
  "Ma Khin Lay Nwe", "U Than Htut", "Daw Win Win Maw", "Ko Aung Kyaw Oo", "Ma Htet Htet Aung"
];

const myanmarAddresses = [
  "Kamayut, Yangon", "Hledan, Yangon", "Sanchaung, Yangon", "Tamwe, Yangon", "Yankin, Yangon",
  "Bahan, Yangon", "Kyauktada, Yangon", "Mayangone, Yangon", "Insein, Yangon", "Thingangyun, Yangon",
  "Chanayethazan, Mandalay", "Mahaaungmye, Mandalay", "Pyigyitagon, Mandalay", "Aungmyethazan, Mandalay",
  "Taunggyi, Shan State", "Pyin Oo Lwin", "Mawlamyine, Mon State", "Nay Pyi Taw"
];

const paymentMethods: PaymentMethod[] = ["cash", "mobile_payment", "bank_transfer", "card_payment"];

// Generator: 1 Year of Realistic, Consistent Daily Sales (10 - 20 sales per day for 365 days)
export function generateOneYearSalesAndWarranties(): { sales: Sale[]; warranties: Warranty[] } {
  const sales: Sale[] = [];
  const warranties: Warranty[] = [];

  const endDate = new Date(2026, 8, 27, 18, 0, 0); // 2026-09-27
  let invoiceCounter = 1000;
  let warrantyCounter = 1000;

  // Generate for past 365 days (from 2025-09-28 to 2026-09-27)
  for (let dayOffset = 364; dayOffset >= 0; dayOffset--) {
    const currentDay = new Date(endDate);
    currentDay.setDate(endDate.getDate() - dayOffset);
    const dateStr = currentDay.toISOString().split("T")[0];

    // Daily sales count between 10 and 20 (deterministic pseudo-random based on dayOffset)
    const dailyCount = 10 + (Math.abs(Math.sin(dayOffset * 7.13 + 3.2)) * 11) | 0; // 10 to 20

    for (let sIdx = 0; sIdx < dailyCount; sIdx++) {
      invoiceCounter++;
      warrantyCounter++;

      const hour = 9 + Math.floor((sIdx / dailyCount) * 11); // 9:00 to 20:00
      const minute = (sIdx * 17 + dayOffset * 3) % 60;
      const second = (sIdx * 23) % 60;
      const saleTimestamp = `${dateStr}T${String(hour).padStart(2, "0")}:${String(minute).padStart(2, "0")}:${String(second).padStart(2, "0")}Z`;

      const customerIndex = (dayOffset * 13 + sIdx * 7) % myanmarCustomerNames.length;
      const customerName = myanmarCustomerNames[customerIndex];
      const customerPhone = `09${700000000 + ((dayOffset * 83 + sIdx * 97) % 299999999)}`;
      const customerAddress = myanmarAddresses[(dayOffset + sIdx) % myanmarAddresses.length];
      const paymentMethod = paymentMethods[(dayOffset + sIdx * 3) % paymentMethods.length];

      // Select 1 or 2 laptop items from the 40 laptop catalog
      const laptop1 = initialLaptops[(dayOffset * 3 + sIdx * 2) % initialLaptops.length];
      const qty1 = 1;
      const item1: SaleItem = {
        id: `si-${invoiceCounter}-1`,
        sale_id: `sale-${invoiceCounter}`,
        laptop_id: laptop1.id,
        laptop_brand: laptop1.brand?.name || "Dell",
        laptop_model: laptop1.model,
        serial_number: `${laptop1.serial_number}-U${(sIdx + dayOffset) % 100}`,
        quantity: qty1,
        unit_price: laptop1.selling_price,
        discount: 0,
        total_price: laptop1.selling_price * qty1,
        warranty_period_months: laptop1.warranty_period_months,
        created_at: saleTimestamp,
      };

      const items: SaleItem[] = [item1];
      let subtotal = item1.total_price;

      // 15% chance of buying 2 items
      if (sIdx % 7 === 0) {
        const laptop2 = initialLaptops[(dayOffset * 5 + sIdx * 3 + 1) % initialLaptops.length];
        const item2: SaleItem = {
          id: `si-${invoiceCounter}-2`,
          sale_id: `sale-${invoiceCounter}`,
          laptop_id: laptop2.id,
          laptop_brand: laptop2.brand?.name || "Lenovo",
          laptop_model: laptop2.model,
          serial_number: `${laptop2.serial_number}-U${(sIdx + dayOffset + 50) % 100}`,
          quantity: 1,
          unit_price: laptop2.selling_price,
          discount: 0,
          total_price: laptop2.selling_price,
          warranty_period_months: laptop2.warranty_period_months,
          created_at: saleTimestamp,
        };
        items.push(item2);
        subtotal += item2.total_price;
      }

      // Small promotional discount on select transactions
      const discount = sIdx % 6 === 0 ? 20000 : sIdx % 11 === 0 ? 50000 : 0;
      const total = subtotal - discount;

      const invoiceNum = `INV-${dateStr.replace(/-/g, "")}-${String(invoiceCounter).slice(-4)}`;

      const saleRecord: Sale = {
        id: `sale-${invoiceCounter}`,
        invoice_number: invoiceNum,
        customer_name: customerName,
        customer_phone: customerPhone,
        customer_email: `${customerName.toLowerCase().replace(/\s+/g, "")}${invoiceCounter % 99}@gmail.com`,
        customer_address: customerAddress,
        customer_notes: null,
        subtotal,
        discount,
        total,
        payment_method: paymentMethod,
        payment_status: "paid",
        sale_date: saleTimestamp,
        staff_id: sIdx % 2 === 0 ? "user-admin" : "user-staff-1",
        notes: "Full payment received.",
        created_at: saleTimestamp,
        items,
      };

      sales.push(saleRecord);

      // Create Warranty records for items
      items.forEach((item, itemIdx) => {
        const endWDate = new Date(currentDay);
        endWDate.setMonth(endWDate.getMonth() + item.warranty_period_months);
        const isExpired = endWDate < new Date(2026, 8, 27);

        warranties.push({
          id: `war-${warrantyCounter}-${itemIdx}`,
          sale_id: saleRecord.id,
          laptop_id: item.laptop_id,
          serial_number: item.serial_number || `${item.laptop_brand}-SN-${warrantyCounter}`,
          laptop_model: `${item.laptop_brand} ${item.laptop_model}`,
          customer_name: customerName,
          customer_phone: customerPhone,
          start_date: saleTimestamp,
          end_date: endWDate.toISOString(),
          warranty_period_months: item.warranty_period_months,
          status: isExpired ? "expired" : "active",
          terms: "1 Year Standard Hardware Parts & Labor Warranty by YaungMal-PyinMal.",
          created_at: saleTimestamp,
        });
      });
    }
  }

  return { sales, warranties };
}

const { sales: generatedSales, warranties: generatedWarranties } = generateOneYearSalesAndWarranties();

export const initialSales: Sale[] = generatedSales;
export const initialWarranties: Warranty[] = generatedWarranties;

// Realistic Service Jobs
export const initialServices: LaptopService[] = [
  {
    id: "srv-201",
    service_ticket_no: "SRV-2026-0001",
    customer_name: "Ko Aung Kyaw",
    customer_phone: "09791234567",
    customer_email: "aungkyaw@gmail.com",
    customer_address: "Kamayut, Yangon",
    laptop_brand: "Dell",
    laptop_model: "XPS 15 9500",
    serial_number: "DLXPS95-1234",
    received_date: "2026-09-25T10:00:00Z",
    problem_description: "Screen flickering on battery power. Fan noisy under load.",
    diagnosis: "EDP display cable loose connection, thermal paste dried up causing thermal throttling.",
    repair_details: "Cleaned internal fans, re-applied Arctic MX-4 thermal paste, reseated display ribbon cable.",
    service_cost: 65000,
    paid_amount: 65000,
    payment_method: "cash",
    payment_status: "paid",
    completed_date: "2026-09-26T14:00:00Z",
    delivered_date: "2026-09-26T16:30:00Z",
    status: "delivered",
    notes: "Customer tested in shop and approved.",
    history: [
      { id: "h-1", service_id: "srv-201", status: "received", notes: "Device received at counter", created_at: "2026-09-25T10:00:00Z" },
      { id: "h-2", service_id: "srv-201", status: "checking", notes: "Hardware inspection started", created_at: "2026-09-25T12:00:00Z" },
      { id: "h-3", service_id: "srv-201", status: "repairing", notes: "Thermal servicing & cable reseating", created_at: "2026-09-26T09:00:00Z" },
      { id: "h-4", service_id: "srv-201", status: "completed", notes: "Bench stress test passed", created_at: "2026-09-26T14:00:00Z" },
      { id: "h-5", service_id: "srv-201", status: "delivered", notes: "Delivered to customer", created_at: "2026-09-26T16:30:00Z" },
    ],
  },
  {
    id: "srv-202",
    service_ticket_no: "SRV-2026-0002",
    customer_name: "Ma Su Mon",
    customer_phone: "09971234567",
    customer_email: "sumon@gmail.com",
    customer_address: "Sanchaung, Yangon",
    laptop_brand: "HP",
    laptop_model: "Pavilion 14",
    serial_number: "HP-PAV-14-88",
    received_date: "2026-09-26T11:00:00Z",
    problem_description: "Battery not charging. Shuts down immediately when adapter disconnected.",
    diagnosis: "Dead battery cells. Internal battery replacement required.",
    repair_details: "Ordered replacement 3-cell 41Wh battery from supplier.",
    service_cost: 95000,
    paid_amount: 30000,
    payment_method: "mobile_payment",
    payment_status: "partial",
    completed_date: null,
    delivered_date: null,
    status: "waiting_for_parts",
    notes: "Deposit 30,000 MMK paid via KPay. Awaiting battery shipment.",
    history: [
      { id: "h-6", service_id: "srv-202", status: "received", notes: "Received unit", created_at: "2026-09-26T11:00:00Z" },
      { id: "h-7", service_id: "srv-202", status: "checking", notes: "Diagnosed battery failure", created_at: "2026-09-26T13:00:00Z" },
      { id: "h-8", service_id: "srv-202", status: "waiting_for_parts", notes: "Part ordered", created_at: "2026-09-26T15:00:00Z" },
    ],
  },
  {
    id: "srv-203",
    service_ticket_no: "SRV-2026-0003",
    customer_name: "Ko Min Min",
    customer_phone: "09420998877",
    customer_email: "minmin@gmail.com",
    customer_address: "Tamwe, Yangon",
    laptop_brand: "Lenovo",
    laptop_model: "Legion 5 15ACH6",
    serial_number: "LNV-LEG5-77",
    received_date: "2026-09-27T09:30:00Z",
    problem_description: "Windows blue screen error (BSOD) and very slow boot.",
    diagnosis: "Checking NVMe SSD health and RAM integrity.",
    repair_details: null,
    service_cost: 35000,
    paid_amount: 0,
    payment_method: null,
    payment_status: "unpaid",
    completed_date: null,
    delivered_date: null,
    status: "checking",
    notes: "Initial checking in progress.",
    history: [
      { id: "h-9", service_id: "srv-203", status: "received", notes: "Received ticket", created_at: "2026-09-27T09:30:00Z" },
      { id: "h-10", service_id: "srv-203", status: "checking", notes: "Diagnosing BSOD error", created_at: "2026-09-27T10:15:00Z" },
    ],
  },
];

export const initialProfiles: Profile[] = [
  {
    id: "user-admin",
    full_name: "Shop Admin (Owner)",
    email: "admin@yaungmal.com",
    phone: "0911223344",
    role: "admin",
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "user-staff-1",
    full_name: "Ko Kyaw Zin (Staff)",
    email: "staff@yaungmal.com",
    phone: "0999887766",
    role: "staff",
    is_active: true,
    created_at: "2026-02-01T00:00:00Z",
    updated_at: "2026-02-01T00:00:00Z",
  },
];

export const initialShopSettings: ShopSettings = {
  id: "default",
  shop_name: "YaungMal-PyinMal Laptop Shop",
  shop_address: "No. 124, Pyay Road, Kamayut Township, Yangon",
  shop_phone: "09-777-888-999 / 09-555-666-777",
  shop_email: "support@yaungmal-pyinmal.com",
  invoice_header: "Laptop Sales, Accessories & Quality Repair Services",
  invoice_footer: "Thank you for your purchase! / ဝယ်ယူအားပေးမှုအတွက် အထူးကျေးဇူးတင်ရှိပါသည်။",
  currency: "MMK",
  date_format: "DD/MM/YYYY",
  low_stock_threshold: 3,
};
